In [ ]:
# part 1
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
a0 = np.zeros(10)
print(a0,'\n')


a1 = np.ones(10)
print(a1,'\n')


# a5 = np.ones(10)*5
a5 = np.full(10,5)

print(a5,'\n')

res = np.concatenate((a0,a1,a5))
print(res)

Mounted at /content/drive
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[5 5 5 5 5 5 5 5 5 5] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# part 1 
# 2)

import numpy as np
a = np.array([x for x in range(10,50+1) if (x%2==0)])

print(a)



[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# part 1 
# 3)

import numpy as np

a = np.random.random()
print(a)


0.7372161925917208


In [ ]:
import numpy as np

n = (int)(input('Number of rows of random between 0,1 : '))
m = (int)(input('Number of cols of random between 0,1 : '))

a = np.random.random((n,m))




np.savetxt("a1p14.txt",a)

content = np.loadtxt("a1p14.txt")

print('Content of the file : ',content)

Number of rows of random between 0,1 : 5
Number of cols of random between 0,1 : 4
Content of the file :  [[0.68781649 0.2666304  0.77730112 0.97985752]
 [0.85367395 0.0213521  0.70642571 0.29444973]
 [0.26963422 0.90122772 0.8515995  0.83336591]
 [0.20893182 0.72300406 0.83334909 0.64841937]
 [0.73178477 0.86051566 0.28093878 0.58986743]]


In [ ]:

# part 2
# 1)

import numpy as np
import pandas as pd
import matplotlib.image as img

imageMatrix = img.imread('/content/drive/MyDrive/5th sem/ML/MLLAB/wall.png',0)

print(imageMatrix.shape)

# converting the 3D into 2D matrix, first dimension is same and second is multiplication of the another 2 dimensions
imageMatrixReshape = imageMatrix.reshape((imageMatrix.shape[0],imageMatrix.shape[1]*imageMatrix.shape[2]))

#data frame is similar to sql table it has col and row
df = pd.DataFrame(imageMatrixReshape)

# print(df)
# while writing to csv, if index = false, then data will be written without indices( which are present in data frame)

df.to_csv('a1p21.csv',index=False)

print(len(df))
print(len(df.columns))
print(df)
# # extracting only n-1 cols and m-1 cols
# # while reading csv it will read along with indices, although we excluded indices from dataframe to csv intially

newDf = pd.read_csv('a1p21.csv',nrows=len(df)-1,usecols=range(len(df.columns)-1))
print(newDf)
# print(len(newDf))
# print(len(newDf.columns))








(1308, 736, 3)
1308
2208
      0     1     2     3     4     5     ...  2202  2203  2204  2205  2206  2207
0        0     0     0     0     0     0  ...     0     0     0     0     0     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     0     0     0  ...     0     0     0     0     0     0
3        0     0     0     0     0     0  ...     0     0     0     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
1303     0     0     0     0     0     0  ...     0     0     0     0     0     0
1304     0     0     0     0     0     0  ...     0     0     0     0     0     0
1305     0     0     0     0     0     0  ...     0     0     0     0     0     0
1306     0     0     0     0     0     0  ...     0     0     0     0     0     0
1307     0     0     0     0     0     0  ...     0     0     0     0    

In [ ]:

# part 2
# 2)

import numpy as np
import pandas as pd
import matplotlib.image as img

# imageMatrix = img.imread('/content/drive/My Drive/5th sem/ML/MLLAB/sample1.jpg')

# # converting the 3D into 2D matrix, first dimension is same and second is multiplication of the another 2 dimensions
# imageMatrixReshape = imageMatrix.reshape((imageMatrix.shape[0],imageMatrix.shape[1]*imageMatrix.shape[2]))

# #data frame is similar to sql table it has col and row
# df = pd.DataFrame(imageMatrixReshape)
# # print(df)
# # while writing to csv, if index = false, then data will be written without indices( which are present in data frame)

# df.to_csv('a1p21.csv',index=False)

# print(len(df))
# print(len(df.columns))
# extracting only n-1 cols and m-1 cols
# while reading csv it will read along with indices, although we excluded indices from dataframe to csv intially

newDf = pd.read_csv('a1p21.csv',nrows=len(df)-1,usecols=range(len(df.columns)-1))

print(len(newDf))
print(len(newDf.columns))
print(newDf)








1307
2207
      0  1  2  3  4  5  6  7  ...  2199  2200  2201  2202  2203  2204  2205  2206
0     0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
1     0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
2     0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
3     0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
4     0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
...  .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   ...   ...
1302  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
1303  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
1304  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
1305  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0
1306  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0     0     0

[1307

In [ ]:
# part 2
# 3)
import pandas as pd
from datetime import date
datenow = pd.to_datetime("now").date()

print(datenow)
print((date.today()))



2021-11-02
2021-11-02


In [ ]:
# part 3
# 1)
from datetime import date

dob_year = (int)(input("Enter Year of Birth : "))

dob_month = (int)(input("Enter Month of Birth : "))

dob_day = (int)(input("Enter Date of Birth : "))

presentDate = date.today()

diff = 0
if(presentDate.month <= dob_month):

 if(presentDate.month < dob_month):
   diff = 1
 elif(presentDate.day < dob_day):
      diff = 1
        
 

currAge = (presentDate.year - dob_year) - diff
print('Age is : ',currAge)



Enter Year of Birth : 2002
Enter Month of Birth : 8
Enter Date of Birth : 3
Age is :  19
